[package]
name = "subtitle_cleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
clap = "2.3.3"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
debug = false