[package]
name = "subtitle_cleaner"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.5"
rfd = "^0.13.0"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
debug = false